import type { AstroComponentFactory } from 'astro/runtime/server/index.js';
import DemoWrapper from './components/Demo/Demo.astro';
import Kbd from './components/Kbd.astro';
import Link from './components/Link.astro';
import CodeInline from './components/mdx/CodeInline.astro';
import Figcaption from './components/mdx/Figcaption.astro';
import Figure from './components/mdx/Figure.astro';
import H1 from './components/mdx/H1.astro';
import H2 from './components/mdx/H2.astro';
import H3 from './components/mdx/H3.astro';
import H4 from './components/mdx/H4.astro';
import H5 from './components/mdx/H5.astro';
import H6 from './components/mdx/H6.astro';
import Li from './components/mdx/Li.astro';
import Ol from './components/mdx/Ol.astro';
import P from './components/mdx/P.astro';
import Pre from './components/mdx/Pre.astro';
import Strong from './components/mdx/Strong.astro';
import TableBody from './components/mdx/TableBody.astro';
import TableHead from './components/mdx/TableHead.astro';
import TableRoot from './components/mdx/TableRoot.astro';
import TableRow from './components/mdx/TableRow.astro';
import TableTd from './components/mdx/TableTd.astro';
import TableTh from './components/mdx/TableTh.astro';
import Ul from './components/mdx/Ul.astro';
import MetaWrapper from './components/Meta.astro';
import ReleaseTimeline from './components/ReleaseTimeline.astro';
import AttributesReferenceTable from './components/ReferenceTable/AttributesReferenceTable.astro';
import CssVariablesReferenceTable from './components/ReferenceTable/CssVariablesReferenceTable.astro';
import ParametersReferenceTable from './components/ReferenceTable/ParametersReferenceTable.astro';
import PropsReferenceTable from './components/ReferenceTable/PropsReferenceTable.astro';
import ReturnValueReferenceTable from './components/ReferenceTable/ReturnValueReferenceTable.astro';
import SubtitleWrapper from './components/Subtitle.astro';

export const mdxComponents: Record<string, AstroComponentFactory | string> = {
  a: Link as any,
  h1: H1 as any,
  h2: H2 as any,
  h3: H3 as any,
  h4: H4 as any,
  h5: H5 as any,
  h6: H6 as any,
  p: P as any,
  li: Li as any,
  ul: Ul as any,
  ol: Ol as any,
  kbd: Kbd as any,
  strong: Strong as any,
  code: CodeInline as any,
  figure: Figure as any,
  figcaption: Figcaption as any,
  pre: Pre as any,
  table: TableRoot as any,
  thead: TableHead as any,
  tbody: TableBody as any,
  tr: TableRow as any,
  th: TableTh as any,
  td: TableTd as any,
  Demo: DemoWrapper as any,
  Subtitle: SubtitleWrapper as any,
  Meta: MetaWrapper as any,
  ReleaseTimeline: ReleaseTimeline as any,
  PropsReferenceTable: PropsReferenceTable as any,
  AttributesReferenceTable: AttributesReferenceTable as any,
  CssVariablesReferenceTable: CssVariablesReferenceTable as any,
  ParametersReferenceTable: ParametersReferenceTable as any,
  ReturnValueReferenceTable: ReturnValueReferenceTable as any,
};
